# Generated by Django 5.0.2 on 2024-06-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignUpModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.TextField(max_length=100)),
                ("Last_Name", models.TextField(max_length=100)),
                ("Email", models.EmailField(max_length=100)),
                ("Phone_No", models.BigIntegerField()),
                ("Password", models.CharField(max_length=100)),
            ],
        ),
    ]
