# Generated by Django 5.0.2 on 2024-06-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signupmodel",
            name="First_Name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="signupmodel",
            name="Last_Name",
            field=models.CharField(max_length=100),
        ),
    ]
