# Generated by Django 5.0.2 on 2024-06-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copper", "0002_alter_signupmodel_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="signupmodel",
            name="Conform_password",
            field=models.CharField(default=40, max_length=100),
        ),
    ]
